name:                rel8-check
version:             0.1.0.0
github:              "chrisdone/rel8-check"
license:             BSD-3-Clause
author:              "Chris Done"
maintainer:          "chris@chrisdone.com"
copyright:           "2025 Chris Done"

extra-source-files:
- README.md
- CHANGELOG.md

dependencies:
- base >= 4.7 && < 5
- rel8
- hasql
- bytestring

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints

executables:
  rel8-check:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - hspec
